/**
 * radio bean:
 *
 *  {
    "id": 2065414648,
    "type": 1,
    "name": "蔡毅：林军兄弟，一路走好 By 主播酥羊",
    "copywriter": "编辑推荐：向白衣天使们致敬！",
    "picUrl": "http://p1.music.126.net/3eVsRs1tAz9UTTHcrTgghA==/109951164705309145.jpg",
    "canDislike": false,
    "trackNumberUpdateTime": null,
    "program": {
        "mainSong": {
            "name": "蔡毅：林军兄弟，一路走好 By 主播酥羊",
            "id": 1423153041,
            "position": 0,
            "alias": [],
            "status": 0,
            "fee": 0,
            "copyrightId": 0,
            "disc": "",
            "no": 0,
            "artists": [{
                "name": "",
                "id": 0,
                "picId": 0,
                "img1v1Id": 0,
                "briefDesc": "",
                "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                "albumSize": 0,
                "alias": [],
                "trans": "",
                "musicSize": 0,
                "topicPerson": 0
            }],
            "album": {
                "name": null,
                "id": 0,
                "type": null,
                "size": 0,
                "picId": 0,
                "blurPicUrl": null,
                "companyId": 0,
                "pic": 0,
                "picUrl": "http://p1.music.126.net/UeTuwE7pvjBpypWLudqukA==/3132508627578625.jpg",
                "publishTime": 0,
                "description": "",
                "tags": "",
                "company": null,
                "briefDesc": "",
                "artist": {
                    "name": "",
                    "id": 0,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                },
                "songs": [],
                "alias": [],
                "status": 0,
                "copyrightId": 0,
                "commentThreadId": "R_AL_3_0",
                "artists": [{
                    "name": "",
                    "id": 0,
                    "picId": 0,
                    "img1v1Id": 0,
                    "briefDesc": "",
                    "picUrl": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "img1v1Url": "http://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg",
                    "albumSize": 0,
                    "alias": [],
                    "trans": "",
                    "musicSize": 0,
                    "topicPerson": 0
                }],
                "subType": null,
                "transName": null,
                "mark": 0
            },
            "starred": false,
            "popularity": 5,
            "score": 5,
            "starredNum": 0,
            "duration": 727080,
            "playedNum": 0,
            "dayPlays": 0,
            "hearTime": 0,
            "ringtone": null,
            "crbt": null,
            "audition": null,
            "copyFrom": "",
            "commentThreadId": "R_SO_4_1423153041",
            "rtUrl": null,
            "ftype": 0,
            "rtUrls": [],
            "copyright": 0,
            "transName": null,
            "sign": null,
            "mark": 0,
            "mvid": 0,
            "bMusic": {
                "name": null,
                "id": 4490485041,
                "size": 17464003,
                "extension": "mp3",
                "sr": 48000,
                "dfsId": 0,
                "bitrate": 192000,
                "playTime": 727080,
                "volumeDelta": 0
            },
            "mp3Url": null,
            "rtype": 0,
            "rurl": null,
            "hMusic": null,
            "mMusic": {
                "name": null,
                "id": 4490485041,
                "size": 17464003,
                "extension": "mp3",
                "sr": 48000,
                "dfsId": 0,
                "bitrate": 192000,
                "playTime": 727080,
                "volumeDelta": 0
            },
            "lMusic": {
                "name": null,
                "id": 4490485041,
                "size": 17464003,
                "extension": "mp3",
                "sr": 48000,
                "dfsId": 0,
                "bitrate": 192000,
                "playTime": 727080,
                "volumeDelta": 0
            }
        },
        "songs": null,
        "dj": {
            "defaultAvatar": false,
            "province": 410000,
            "authStatus": 0,
            "followed": false,
            "avatarUrl": "http://p1.music.126.net/0Ej6kb0KzIZFhy-X0zhIJQ==/18943485835154415.jpg",
            "accountStatus": 0,
            "gender": 1,
            "city": 410100,
            "birthday": 351273600000,
            "userId": 45686703,
            "userType": 0,
            "nickname": "德芙_先生",
            "signature": "喜欢我们的主播请多多打赏哦",
            "description": "",
            "detailDescription": "",
            "avatarImgId": 18943485835154416,
            "backgroundImgId": 2002210674180200,
            "backgroundUrl": "http://p1.music.126.net/45Nu4EqvFqK_kQj6BkPwcw==/2002210674180200.jpg",
            "authority": 0,
            "mutual": false,
            "expertTags": null,
            "experts": null,
            "djStatus": 10,
            "vipType": 0,
            "remarkName": null,
            "backgroundImgIdStr": "2002210674180200",
            "avatarImgIdStr": "18943485835154415",
            "avatarImgId_str": "18943485835154415",
            "brand": "读书有疑"
        },
        "blurCoverUrl": "http://music.163.com/api/dj/img/blur/109951164705309145",
        "radio": {
            "id": 331833058,
            "dj": null,
            "name": "读书有疑",
            "picUrl": "http://p1.music.126.net/INFqWVwLDzppjv9mJSXq_w==/1406275374339153.jpg",
            "desc": "",
            "subCount": 28230,
            "programCount": 808,
            "createTime": 1457261643694,
            "categoryId": 6,
            "category": "美文读物",
            "radioFeeType": 0,
            "feeScope": 0,
            "buyed": false,
            "videos": null,
            "finished": false,
            "underShelf": false,
            "purchaseCount": 0,
            "price": 0,
            "originalPrice": 0,
            "discountPrice": null,
            "lastProgramCreateTime": 1581650730603,
            "lastProgramName": null,
            "lastProgramId": 2065414648,
            "picId": 1406275374339153,
            "rcmdText": "带着疑问读书，看到更大世界",
            "hightQuality": false,
            "whiteList": false,
            "composeVideo": false
        },
        "subscribedCount": 0,
        "reward": false,
        "mainTrackId": 1423153041,
        "serialNum": 808,
        "listenerCount": 1107,
        "name": "蔡毅：林军兄弟，一路走好 By 主播酥羊",
        "id": 2065414648,
        "createTime": 1581650730603,
        "description": "微博用户武汉市中心医院疼痛科主任蔡毅@疼痛科小蔡 2月11日微博",
        "userId": 45686703,
        "coverUrl": "http://p1.music.126.net/3eVsRs1tAz9UTTHcrTgghA==/109951164705309145.jpg",
        "commentThreadId": "A_DJ_1_2065414648",
        "channels": ["有声读物"],
        "titbits": null,
        "titbitImages": null,
        "pubStatus": 1,
        "trackCount": 0,
        "bdAuditStatus": -1,
        "programFeeType": 0,
        "buyed": false,
        "programDesc": null,
        "h5Links": [],
        "coverId": 109951164705309150,
        "adjustedPlayCount": 1107,
        "canReward": true,
        "auditStatus": 0,
        "publish": true,
        "duration": 727080,
        "isPublish": true
    },
    "alg": "featured"
}
 */

Component({
  properties: {
    radio: {
      type: Object,
      value: {}
    }
  }
})
